#pragma once
class EditorComponent;

class FlammableWindow : public wi::gui::Window
{
public:
	void Create(EditorComponent* editor);

	EditorComponent* editor = nullptr;
	wi::ecs::Entity entity = wi::ecs::INVALID_ENTITY;
	void SetEntity(wi::ecs::Entity entity);

	wi::gui::Button igniteButton;
	wi::gui::Button extinguishButton;
	wi::gui::Slider igniteIntensitySlider;
	wi::gui::CheckBox forceExtinguishCheckBox;

	wi::gui::CheckBox activeCheckBox;
	wi::gui::CheckBox burningCheckBox;
	wi::gui::CheckBox burntCheckBox;
	wi::gui::CheckBox autoGeneratedCheckBox;

	wi::gui::Slider flammabilitySlider;
	wi::gui::Slider fuelSlider;
	wi::gui::Slider burnRateSlider;
	wi::gui::Slider ignitionSlider;
	wi::gui::Slider heatSlider;
	wi::gui::Slider heatDissipationSlider;
	wi::gui::Slider spreadRadiusSlider;
	wi::gui::Slider spreadRateSlider;
	wi::gui::Slider windSensitivitySlider;
	wi::gui::Slider smokeAmountSlider;
	wi::gui::Slider scorchFactorSlider;
	wi::gui::Slider damageSlider;
	wi::gui::Slider cooldownSlider;
	wi::gui::Slider timeSinceIgnitionSlider;

	wi::gui::Label stateLabel;

	void ResizeLayout() override;
};
