#include "stdafx.h"
#include "FlammableWindow.h"

#include "Editor.h"
#include "wiScene.h"
#include "wiHelper.h"

#include <sstream>
#include <iomanip>

using namespace wi::ecs;
using namespace wi::scene;

void FlammableWindow::Create(EditorComponent* _editor)
{
	editor = _editor;
	wi::gui::Window::Create(ICON_FLAMMABLE " Flammable", wi::gui::Window::WindowControls::COLLAPSE | wi::gui::Window::WindowControls::CLOSE | wi::gui::Window::WindowControls::FIT_ALL_WIDGETS_VERTICAL);
	SetSize(XMFLOAT2(520, 420));

	closeButton.SetTooltip("Delete FlammableComponent");
	OnClose([=](wi::gui::EventArgs args) {
		wi::Archive& archive = editor->AdvanceHistory();
		archive << EditorComponent::HISTORYOP_COMPONENT_DATA;
		editor->RecordEntity(archive, entity);

		editor->GetCurrentScene().flammables.Remove(entity);

		editor->RecordEntity(archive, entity);
		editor->componentsWnd.RefreshEntityTree();
	});

	auto forEachSelected = [this](auto func) {
		return [this, func](wi::gui::EventArgs args) {
			Scene& scene = editor->GetCurrentScene();
			for (const auto& sel : editor->translator.selected)
			{
				FlammableComponent* flammable = scene.flammables.GetComponent(sel.entity);
				if (flammable != nullptr)
				{
					func(*flammable, args);
				}
			}
		};
	};

	auto sceneForEachEntity = [this](auto func) {
		return [this, func](wi::gui::EventArgs args) {
			Scene& scene = editor->GetCurrentScene();
			for (const auto& sel : editor->translator.selected)
			{
				func(scene, sel.entity, args);
			}
		};
	};

	igniteIntensitySlider.Create(0.0f, 5.0f, 1.0f, 10000, "Ignite intensity: ");
	igniteIntensitySlider.SetTooltip("Multiplier applied when igniting the selection.");
	igniteIntensitySlider.SetSize(XMFLOAT2(200, 18));
	AddWidget(&igniteIntensitySlider);

	igniteButton.Create("Ignite");
	igniteButton.SetTooltip("Ignite selected entities using the specified intensity.");
	igniteButton.OnClick(sceneForEachEntity([&](Scene& scene, Entity entity, wi::gui::EventArgs eventArgs) {
		Entity entityRef = entity;
		if (scene.flammables.Contains(entityRef))
		{
			scene.Fire_Ignite(entityRef, igniteIntensitySlider.GetValue());
		}
	}));
	AddWidget(&igniteButton);

	extinguishButton.Create("Extinguish");
	extinguishButton.SetTooltip("Extinguish selected entities. Optionally force immediate shutdown.");
	extinguishButton.OnClick(sceneForEachEntity([&](Scene& scene, Entity entity, wi::gui::EventArgs eventArgs) {
		Entity entityRef = entity;
		if (scene.flammables.Contains(entityRef))
		{
			scene.Fire_Extinguish(entityRef, forceExtinguishCheckBox.GetCheck());
		}
	}));
	AddWidget(&extinguishButton);

	forceExtinguishCheckBox.Create("Force extinguish");
	forceExtinguishCheckBox.SetTooltip("When enabled, fire is quenched instantly and resets cooldown.");
	AddWidget(&forceExtinguishCheckBox);

	activeCheckBox.Create("Active");
	activeCheckBox.SetTooltip("Toggle whether this component can ignite.");
	activeCheckBox.OnClick(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.SetActive(args.bValue);
	}));
	AddWidget(&activeCheckBox);

	burningCheckBox.Create("Burning");
	burningCheckBox.SetTooltip("Force burning state.");
	burningCheckBox.OnClick(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.SetBurning(args.bValue);
		if (args.bValue)
		{
			flammable.SetBurnedOut(false);
		}
	}));
	AddWidget(&burningCheckBox);

	burntCheckBox.Create("Burned out");
	burntCheckBox.SetTooltip("Flag as burned out which prevents reignition until reset.");
	burntCheckBox.OnClick(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.SetBurnedOut(args.bValue);
		if (args.bValue)
		{
			flammable.SetBurning(false);
		}
	}));
	AddWidget(&burntCheckBox);

	autoGeneratedCheckBox.Create("Auto generated");
	autoGeneratedCheckBox.SetTooltip("Mark whether this component was created automatically by the system.");
	autoGeneratedCheckBox.OnClick(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.SetAutoGenerated(args.bValue);
	}));
	AddWidget(&autoGeneratedCheckBox);

	flammabilitySlider.Create(0.0f, 3.0f, 0.6f, 10000, "Flammability: ");
	flammabilitySlider.SetTooltip("Scales how quickly heat accumulates from nearby fires.");
	flammabilitySlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.flammability = args.fValue;
	}));
	AddWidget(&flammabilitySlider);

	fuelSlider.Create(0.0f, 600.0f, 60.0f, 10000, "Fuel: ");
	fuelSlider.SetTooltip("Total virtual fuel reserve in seconds * burn rate.");
	fuelSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.fuel = std::max(0.0f, args.fValue);
		flammable.initialFuel = std::max(flammable.initialFuel, flammable.fuel);
	}));
	AddWidget(&fuelSlider);

	burnRateSlider.Create(0.0f, 120.0f, 10.0f, 10000, "Burn rate: ");
	burnRateSlider.SetTooltip("Fuel consumption per second while burning.");
	burnRateSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.burnRate = args.fValue;
	}));
	AddWidget(&burnRateSlider);

	ignitionSlider.Create(0.0f, 120.0f, 30.0f, 10000, "Ignition threshold: ");
	ignitionSlider.SetTooltip("Heat accumulation required before ignition.");
	ignitionSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.ignition = args.fValue;
	}));
	AddWidget(&ignitionSlider);

	heatSlider.Create(0.0f, 200.0f, 0.0f, 10000, "Heat: ");
	heatSlider.SetTooltip("Current stored heat. Adjust to prime or cool an object.");
	heatSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.heat = std::max(0.0f, args.fValue);
	}));
	AddWidget(&heatSlider);

	heatDissipationSlider.Create(0.0f, 50.0f, 5.0f, 10000, "Heat dissipation: ");
	heatDissipationSlider.SetTooltip("Rate at which accumulated heat fades when not burning.");
	heatDissipationSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.heatDissipation = args.fValue;
	}));
	AddWidget(&heatDissipationSlider);

	spreadRadiusSlider.Create(0.0f, 30.0f, 4.0f, 10000, "Spread radius: ");
	spreadRadiusSlider.SetTooltip("Maximum distance (in meters) when sharing heat with neighbours.");
	spreadRadiusSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.spreadRadius = args.fValue;
	}));
	AddWidget(&spreadRadiusSlider);

	spreadRateSlider.Create(0.0f, 120.0f, 15.0f, 10000, "Spread rate: ");
	spreadRateSlider.SetTooltip("Rate at which heat is transferred to neighbours per second.");
	spreadRateSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.spreadRate = args.fValue;
	}));
	AddWidget(&spreadRateSlider);

	windSensitivitySlider.Create(0.0f, 5.0f, 1.0f, 10000, "Wind sensitivity: ");
	windSensitivitySlider.SetTooltip("Multiplier applied to wind influence during propagation.");
	windSensitivitySlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.windSensitivity = args.fValue;
	}));
	AddWidget(&windSensitivitySlider);

	smokeAmountSlider.Create(0.0f, 4.0f, 1.0f, 10000, "Smoke amount: ");
	smokeAmountSlider.SetTooltip("Scales smoke emission rate relative to flame intensity.");
	smokeAmountSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.smokeAmount = args.fValue;
	}));
	AddWidget(&smokeAmountSlider);

	scorchFactorSlider.Create(0.0f, 1.0f, 0.35f, 10000, "Scorch factor: ");
	scorchFactorSlider.SetTooltip("Darkening applied to the underlying object when burnt.");
	scorchFactorSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.scorchFactor = args.fValue;
	}));
	AddWidget(&scorchFactorSlider);

	damageSlider.Create(0.0f, 100.0f, 0.0f, 10000, "Accumulated damage: ");
	damageSlider.SetTooltip("Helper value you can repurpose for gameplay damage tracking.");
	damageSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.damage = args.fValue;
	}));
	AddWidget(&damageSlider);

	cooldownSlider.Create(0.0f, 30.0f, 0.0f, 10000, "Cooldown: ");
	cooldownSlider.SetTooltip("Time remaining before automatic reignition becomes possible.");
	cooldownSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.cooldown = std::max(0.0f, args.fValue);
	}));
	AddWidget(&cooldownSlider);

	timeSinceIgnitionSlider.Create(0.0f, 300.0f, 0.0f, 10000, "Time since ignition: ");
	timeSinceIgnitionSlider.SetTooltip("How long the current burn has been active.");
	timeSinceIgnitionSlider.OnSlide(forEachSelected([](FlammableComponent& flammable, wi::gui::EventArgs args) {
		flammable.timeSinceIgnition = std::max(0.0f, args.fValue);
	}));
	AddWidget(&timeSinceIgnitionSlider);

	stateLabel.Create("Status");
	stateLabel.SetWrapEnabled(true);
	AddWidget(&stateLabel);

	SetMinimized(true);
	SetVisible(false);
	SetEntity(INVALID_ENTITY);
}

void FlammableWindow::SetEntity(Entity entity)
{
	this->entity = entity;

	const Scene& scene = editor->GetCurrentScene();
	const FlammableComponent* flammable = scene.flammables.GetComponent(entity);

	if (flammable != nullptr)
	{
		SetEnabled(true);

		activeCheckBox.SetCheck(flammable->IsActive());
		burningCheckBox.SetCheck(flammable->IsBurning());
		burntCheckBox.SetCheck(flammable->IsBurnedOut());
		autoGeneratedCheckBox.SetCheck(flammable->IsAutoGenerated());

		flammabilitySlider.SetValue(flammable->flammability);
		fuelSlider.SetValue(flammable->fuel);
		burnRateSlider.SetValue(flammable->burnRate);
		ignitionSlider.SetValue(flammable->ignition);
		heatSlider.SetValue(flammable->heat);
		heatDissipationSlider.SetValue(flammable->heatDissipation);
		spreadRadiusSlider.SetValue(flammable->spreadRadius);
		spreadRateSlider.SetValue(flammable->spreadRate);
		windSensitivitySlider.SetValue(flammable->windSensitivity);
		smokeAmountSlider.SetValue(flammable->smokeAmount);
		scorchFactorSlider.SetValue(flammable->scorchFactor);
		damageSlider.SetValue(flammable->damage);
		cooldownSlider.SetValue(flammable->cooldown);
		timeSinceIgnitionSlider.SetValue(flammable->timeSinceIgnition);

		std::ostringstream ss;
		ss.setf(std::ios::fixed);
		ss << std::setprecision(2);
		ss << "Intensity: " << flammable->intensity << '\n';
		ss << "Incoming heat: " << flammable->incomingHeat << '\n';
		ss << "Emitter: " << (flammable->fireEmitter != INVALID_ENTITY ? "yes" : "no") << '\n';
		ss << "Smoke: " << (flammable->smokeEmitter != INVALID_ENTITY ? "yes" : "no") << '\n';
		ss << "Distortion: " << (flammable->distortionEmitter != INVALID_ENTITY ? "yes" : "no") << '\n';
		ss << "Sparks: " << (flammable->sparksEmitter != INVALID_ENTITY ? "yes" : "no");
		stateLabel.SetText(ss.str());
	}
	else
	{
		SetEnabled(false);
		stateLabel.SetText("No flammable component on selection.");
	}
}

void FlammableWindow::ResizeLayout()
{
	wi::gui::Window::ResizeLayout();
	layout.margin_left = 160;
	layout.add(igniteIntensitySlider);
	layout.add_right(forceExtinguishCheckBox);
	layout.add_right(igniteButton, extinguishButton);
	layout.add_right(activeCheckBox);
	layout.add_right(burningCheckBox);
	layout.add_right(burntCheckBox);
	layout.add_right(autoGeneratedCheckBox);
	layout.add(flammabilitySlider);
	layout.add(fuelSlider);
	layout.add(burnRateSlider);
	layout.add(ignitionSlider);
	layout.add(heatSlider);
	layout.add(heatDissipationSlider);
	layout.add(spreadRadiusSlider);
	layout.add(spreadRateSlider);
	layout.add(windSensitivitySlider);
	layout.add(smokeAmountSlider);
	layout.add(scorchFactorSlider);
	layout.add(damageSlider);
	layout.add(cooldownSlider);
	layout.add(timeSinceIgnitionSlider);
	layout.add_fullwidth(stateLabel);
}
